package repository

import (
	"context"
	"fmt"
	"strconv"
	"strings"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgxpool"

	"github.com/Anshul563/edvance-project/services/search-service/internal/model"
)

// NewPostgres connects to the database and verifies it is
// reachable.
func NewPostgres(ctx context.Context, databaseURL string) (*pgxpool.Pool, error) {
	config, err := pgxpool.ParseConfig(databaseURL)
	if err != nil {
		return nil, err
	}

	pool, err := pgxpool.NewWithConfig(ctx, config)
	if err != nil {
		return nil, err
	}

	if err := pool.Ping(ctx); err != nil {
		pool.Close()
		return nil, err
	}

	return pool, nil
}

// postgresRepository is the PostgreSQL full-text implementation of
// SearchRepository. The search_vector column is a generated
// STORED column, so it is always synchronized with the indexed
// text without triggers or repository-side recomputation.
type postgresRepository struct {
	db *pgxpool.Pool
}

// NewSearchRepository returns a PostgreSQL-backed SearchRepository.
func NewSearchRepository(db *pgxpool.Pool) SearchRepository {
	return &postgresRepository{db: db}
}

// Upsert inserts or updates a search document. It is idempotent:
// repeated upserts for the same (source_type, source_id) update the
// existing row rather than creating duplicates. The document id is
// generated by the database and preserved across updates.
func (r *postgresRepository) Upsert(ctx context.Context, doc *model.SearchDocument) error {
	tags := doc.Tags
	if tags == nil {
		tags = map[string]any{}
	}
	metadata := doc.Metadata
	if metadata == nil {
		metadata = map[string]any{}
	}

	const query = `
		INSERT INTO search_documents (
			source_type, source_id, owner_id, title, description, body,
			thumbnail_url, canonical_url, visibility, language, category,
			tags, metadata, published_at
		) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
		ON CONFLICT (source_type, source_id) DO UPDATE SET
			title = EXCLUDED.title,
			description = EXCLUDED.description,
			body = EXCLUDED.body,
			thumbnail_url = EXCLUDED.thumbnail_url,
			canonical_url = EXCLUDED.canonical_url,
			visibility = EXCLUDED.visibility,
			language = EXCLUDED.language,
			category = EXCLUDED.category,
			tags = EXCLUDED.tags,
			metadata = EXCLUDED.metadata,
			published_at = EXCLUDED.published_at,
			indexed_at = NOW(),
			updated_at = NOW()`

	args := []any{
		doc.SourceType,
		doc.SourceID,
		doc.OwnerID,
		doc.Title,
		doc.Description,
		doc.Body,
		doc.ThumbnailURL,
		doc.CanonicalURL,
		doc.Visibility,
		doc.Language,
		doc.Category,
		tags,
		metadata,
		doc.PublishedAt,
	}

	if _, err := r.db.Exec(ctx, query, args...); err != nil {
		return fmt.Errorf("upsert search document: %w", err)
	}

	return nil
}

// Delete removes a search document by its source identity.
func (r *postgresRepository) Delete(ctx context.Context, sourceType string, sourceID uuid.UUID) error {
	const query = `DELETE FROM search_documents WHERE source_type = $1 AND source_id = $2`

	tag, err := r.db.Exec(ctx, query, sourceType, sourceID)
	if err != nil {
		return fmt.Errorf("delete search document: %w", err)
	}
	if tag.RowsAffected() == 0 {
		return ErrNotFound
	}

	return nil
}

// Search performs relevance-ranked full-text search. The query is
// passed to websearch_to_tsquery as a bound parameter, so it can
// never inject SQL. Filters are appended as separate bound
// parameters, and sort order is selected from a fixed whitelist.
func (r *postgresRepository) Search(
	ctx context.Context,
	query string,
	opts SearchOptions,
) ([]*model.SearchResultItem, int64, error) {
	predicates := []string{"visibility = 'public'"}
	args := []any{query}

	predicates = append(predicates, "search_vector @@ websearch_to_tsquery('english', $1)")

	if opts.Type != "" && opts.Type != "all" {
		predicates = append(predicates, "source_type = $"+strconv.Itoa(len(args)+1))
		args = append(args, opts.Type)
	}
	if opts.Category != "" {
		predicates = append(predicates, "category = $"+strconv.Itoa(len(args)+1))
		args = append(args, opts.Category)
	}
	if opts.Language != "" {
		predicates = append(predicates, "language = $"+strconv.Itoa(len(args)+1))
		args = append(args, opts.Language)
	}

	where := "WHERE " + strings.Join(predicates, " AND ")

	countQuery := "SELECT count(*) FROM search_documents " + where
	var total int64
	if err := r.db.QueryRow(ctx, countQuery, args...).Scan(&total); err != nil {
		return nil, 0, fmt.Errorf("search count: %w", err)
	}

	rankExpr := "ts_rank(search_vector, websearch_to_tsquery('english', $1))"

	orderBy := "ORDER BY " + rankExpr + " DESC, published_at DESC NULLS LAST, title ASC"
	if opts.Sort == "newest" {
		orderBy = "ORDER BY published_at DESC NULLS LAST, title ASC"
	}

	limitArg := len(args) + 1
	offsetArg := len(args) + 2
	args = append(args, opts.Limit, opts.Offset)

	querySQL := `
		SELECT id, source_type, source_id, owner_id, title, description,
		       thumbnail_url, canonical_url, visibility, language, category,
		       published_at, ` + rankExpr + ` AS rank
		FROM search_documents
		` + where + `
		` + orderBy + `
		LIMIT $` + strconv.Itoa(limitArg) + ` OFFSET $` + strconv.Itoa(offsetArg)

	rows, err := r.db.Query(ctx, querySQL, args...)
	if err != nil {
		return nil, 0, fmt.Errorf("search query: %w", err)
	}
	defer rows.Close()

	items := make([]*model.SearchResultItem, 0, opts.Limit)
	for rows.Next() {
		doc := &model.SearchDocument{}
		var score float32
		if err := rows.Scan(
			&doc.ID,
			&doc.SourceType,
			&doc.SourceID,
			&doc.OwnerID,
			&doc.Title,
			&doc.Description,
			&doc.ThumbnailURL,
			&doc.CanonicalURL,
			&doc.Visibility,
			&doc.Language,
			&doc.Category,
			&doc.PublishedAt,
			&score,
		); err != nil {
			return nil, 0, fmt.Errorf("scan search result: %w", err)
		}
		items = append(items, &model.SearchResultItem{Document: doc, Score: score})
	}
	if err := rows.Err(); err != nil {
		return nil, 0, fmt.Errorf("search rows: %w", err)
	}

	return items, total, nil
}

// Suggest returns a bounded list of public titles matching the
// query as a case-insensitive prefix. Prefix ILIKE is the right
// semantics for typeahead and is bounded by limit, so it stays
// cheap. The lower(title) text_pattern_ops index supports it.
func (r *postgresRepository) Suggest(
	ctx context.Context,
	query string,
	limit int,
) ([]*model.SearchDocument, error) {
	const querySQL = `
		SELECT id, source_type, title
		FROM search_documents
		WHERE visibility = 'public' AND title ILIKE $1
		ORDER BY title ASC
		LIMIT $2`

	rows, err := r.db.Query(ctx, querySQL, query+"%", limit)
	if err != nil {
		return nil, fmt.Errorf("suggest: %w", err)
	}
	defer rows.Close()

	docs := make([]*model.SearchDocument, 0, limit)
	for rows.Next() {
		doc := &model.SearchDocument{}
		if err := rows.Scan(&doc.ID, &doc.SourceType, &doc.Title); err != nil {
			return nil, fmt.Errorf("scan suggestion: %w", err)
		}
		docs = append(docs, doc)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("suggest rows: %w", err)
	}

	return docs, nil
}

// RecordSearchEvent stores a normalized query with its result
// count for trending analysis. No user identity or raw sensitive
// detail is stored.
func (r *postgresRepository) RecordSearchEvent(
	ctx context.Context,
	normalizedQuery string,
	resultCount int,
) error {
	const query = `
		INSERT INTO search_events (query_normalized, result_count)
		VALUES ($1, $2)`

	if _, err := r.db.Exec(ctx, query, normalizedQuery, resultCount); err != nil {
		return fmt.Errorf("record search event: %w", err)
	}

	return nil
}

// Trending returns the most frequent normalized queries from the
// last 24 hours, derived only from actually recorded events.
func (r *postgresRepository) Trending(ctx context.Context, limit int) ([]model.TrendingItem, error) {
	const query = `
		SELECT query_normalized, count(*) AS count
		FROM search_events
		WHERE created_at >= NOW() - INTERVAL '24 hours'
		GROUP BY query_normalized
		ORDER BY count DESC, query_normalized ASC
		LIMIT $1`

	rows, err := r.db.Query(ctx, query, limit)
	if err != nil {
		return nil, fmt.Errorf("trending: %w", err)
	}
	defer rows.Close()

	items := make([]model.TrendingItem, 0, limit)
	for rows.Next() {
		var item model.TrendingItem
		if err := rows.Scan(&item.Query, &item.Count); err != nil {
			return nil, fmt.Errorf("scan trending: %w", err)
		}
		items = append(items, item)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("trending rows: %w", err)
	}

	return items, nil
}

// Count returns the number of indexed documents, optionally
// filtered by source type.
func (r *postgresRepository) Count(ctx context.Context, sourceType string) (int64, error) {
	if sourceType == "" {
		var total int64
		if err := r.db.QueryRow(ctx, "SELECT count(*) FROM search_documents").Scan(&total); err != nil {
			return 0, fmt.Errorf("count documents: %w", err)
		}
		return total, nil
	}

	var total int64
	if err := r.db.QueryRow(ctx, "SELECT count(*) FROM search_documents WHERE source_type = $1", sourceType).Scan(&total); err != nil {
		return 0, fmt.Errorf("count documents by type: %w", err)
	}
	return total, nil
}
